[opener]
zathura = [
    { run = 'zathura "$@"', orphan = true, desc = "Open with Zathura" }
]
nvim = [
  { run = "nvim '$@'", desc = "Open with Neovim"}
]
[open]
prepend_rules = [
    { name = "*.pdf", use = "zathura" },
    { name = "*.epub", use = "zathura" },
]
